# Generated by Django 5.0.1 on 2024-01-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insuarance",
            "0002_customer_email_customer_phone_no_vehicle_milleage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id_number",
            field=models.IntegerField(unique=True),
        ),
    ]
