# Generated by Django 5.0.1 on 2024-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insuarance", "0003_alter_customer_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default="unknown", max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="dls_no",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
