# Generated by Django 5.0.1 on 2024-01-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insuarance", "0004_customer_address_customer_dls_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="insuarance.customer"
            ),
        ),
    ]
