# Generated by Django 5.0.1 on 2024-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insuarance", "0005_alter_vehicle_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle", name="milleage", field=models.IntegerField(default=0),
        ),
    ]
