# Generated by Django 5.0.1 on 2024-01-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insuarance", "0006_alter_vehicle_milleage"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="insuarance.vehicle",
            ),
        ),
    ]
