# Generated by Django 5.0.1 on 2024-02-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insuarance", "0007_policy_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="dls_no",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="number_plate",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
