# Generated by Django 5.0.1 on 2024-02-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insuarance",
            "0008_alter_customer_dls_no_alter_policy_policy_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_policies",
            field=models.ManyToManyField(
                blank=True, related_name="vehicles", to="insuarance.policy"
            ),
        ),
    ]
